version: '3.8'

services:
  docsmox-cassandra:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "DocsmoxCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
